name: Flask CI

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install libpq-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set environment variables 
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        run: | 
          source venv/bin/activate echo "DATABASE_URL is set"

      - name: Print debugging information
        run: |
          source venv/bin/activate
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site packages: $(ls -l venv/lib/python*/site-packages)"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install libpq-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set environment variables 
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        run: | 
          source venv/bin/activate echo "DATABASE_URL is set"

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          python -m pytest tests/

      - name: Run tests with unittest
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests -p 'test_*.py'


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install libpq-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} #can be found as a part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create my own API Key in render Dashboard > Account Settings